include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore  # freezed @JsonKey trên constructor params
  plugins:
    - custom_lint

linter:
  rules:
    unnecessary_underscores: false